#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

DOKKU_DEPLOY_HOOKS_PREFIX=$(dokku config:get $APP DOKKU_DEPLOY_HOOKS_PREFIX || true)
HOOKS_PATH="${DOKKU_DEPLOY_HOOKS_PREFIX}/deploy/post-deploy"

echo "-----> Running post-deploy hooks"
. $(dirname "$0")/functions
execute_hooks $HOOKS_PATH
