#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

HOOKS_PATH="deploy/post-deploy"

echo "-----> Running post-deploy hooks"
. $(dirname "$0")/functions
execute_hooks $HOOKS_PATH
