#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

HOOKS_PATH="deploy/post-deploy"
HOST_HOOKS_PATH="deploy/host-post-deploy"

. $(dirname "$0")/functions

echo "-----> Running post-deploy hooks"
execute_hooks $HOOKS_PATH

echo "-----> Running host post-deploy hooks"
execute_host_hooks $HOST_HOOKS_PATH
