#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

HOOKS_PATH="deploy/pre-deploy"
HOST_HOOKS_PATH="deploy/host-pre-deploy"

. $(dirname "$0")/functions

echo "-----> Running pre-deploy host hooks"
execute_host_hooks $HOST_HOOKS_PATH

echo "-----> Running pre-deploy hooks"
execute_hooks $HOOKS_PATH
